USE [master]
GO

/****** Object:  Database [ClinicDB]    Script Date: 07/12/2021 6:08:48 pm ******/
CREATE DATABASE [ClinicDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClinicDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ClinicDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClinicDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ClinicDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClinicDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClinicDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClinicDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClinicDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClinicDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClinicDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClinicDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClinicDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClinicDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClinicDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClinicDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClinicDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClinicDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClinicDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClinicDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClinicDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ClinicDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClinicDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClinicDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClinicDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClinicDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClinicDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ClinicDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClinicDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ClinicDB] SET  MULTI_USER 
GO

ALTER DATABASE [ClinicDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClinicDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClinicDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClinicDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ClinicDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ClinicDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ClinicDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ClinicDB] SET  READ_WRITE 
GO


